"use client";

import { useEffect, useState } from "react";
import { Download, History, Trash2 } from "lucide-react";
import type { RateCardDocumentDto, RateProviderDto } from "@nationwide/shared-types";
import { apiClient, ApiError } from "@/lib/api-client";
import { downloadBlob } from "@/lib/utils/download-blob";
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from "@/components/ui/table";
import { TableSkeleton } from "@/components/ui/skeleton";
import { EmptyState, ErrorState } from "@/components/ui/page-state";
import { NativeSelect } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/toast";

export function RateCardHistoryTab() {
  const [docs, setDocs] = useState<RateCardDocumentDto[]>([]);
  const [providers, setProviders] = useState<RateProviderDto[]>([]);
  const [providerFilter, setProviderFilter] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const { showToast } = useToast();

  function load() {
    setIsLoading(true);
    setError(null);
    const query = providerFilter ? `?rateProviderId=${providerFilter}` : "";
    Promise.all([
      apiClient.get<RateCardDocumentDto[]>(`/admin/rate-cards${query}`),
      apiClient.get<RateProviderDto[]>("/admin/rate-providers"),
    ])
      .then(([d, p]) => {
        setDocs(d);
        setProviders(p);
      })
      .catch((err) => {
        setError(err instanceof ApiError ? "Failed to load rate card history." : "Something went wrong.");
      })
      .finally(() => setIsLoading(false));
  }

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [providerFilter]);

  async function handleDownload(doc: RateCardDocumentDto) {
    try {
      const { blob } = await apiClient.getBlob(`/admin/rate-cards/${doc.id}/download`);
      if (blob.size === 0) throw new ApiError(500, "Empty PDF body");
      downloadBlob(blob, `${doc.rateProviderName}-RateCard-v${doc.version}.pdf`);
    } catch {
      showToast({ variant: "error", title: "Couldn't download the rate card." });
    }
  }

  async function handleDelete(doc: RateCardDocumentDto) {
    try {
      await apiClient.delete(`/admin/rate-cards/${doc.id}`);
      showToast({ variant: "success", title: "Rate card deleted" });
      load();
    } catch {
      showToast({ variant: "error", title: "Couldn't delete the rate card." });
    }
  }

  return (
    <div className="page-enter space-y-4">
      <div className="glass flex flex-col justify-between gap-3 rounded-2xl p-4 sm:flex-row sm:items-center">
        <div>
          <p className="text-sm font-semibold text-foreground">Document archive</p>
          <p className="mt-0.5 text-xs text-muted-foreground">Every generated version remains available here.</p>
        </div>
        <NativeSelect
          className="w-full sm:w-56"
          value={providerFilter}
          onChange={(e) => setProviderFilter(e.target.value)}
          aria-label="Filter by provider"
        >
          <option value="">All providers</option>
          {providers.map((p) => (
            <option key={p.id} value={p.id}>
              {p.name}
            </option>
          ))}
        </NativeSelect>
      </div>

      {isLoading && <TableSkeleton columns={7} />}
      {!isLoading && error && <ErrorState message={error} onRetry={load} />}
      {!isLoading && !error && docs.length === 0 && (
        <EmptyState
          icon={<History className="h-8 w-8" aria-hidden />}
          title="No rate cards generated yet"
          description="Generate one from the Rate Cards tab."
        />
      )}
      {!isLoading && !error && docs.length > 0 && (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Generated</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Provider</TableHead>
              <TableHead>Coverage</TableHead>
              <TableHead>Version</TableHead>
              <TableHead>Effective Date</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {docs.map((doc) => (
              <TableRow key={doc.id}>
                <TableCell className="whitespace-nowrap">{new Date(doc.createdAt).toLocaleString("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })}</TableCell>
                <TableCell className="max-w-52 truncate">{doc.generatedByAdminEmail}</TableCell>
                <TableCell className="font-medium">{doc.rateProviderName}</TableCell>
                <TableCell className="max-w-xs">{doc.countryNames.join(", ")}</TableCell>
                <TableCell className="font-mono text-xs font-semibold">v{doc.version}</TableCell>
                <TableCell className="whitespace-nowrap">{doc.effectiveDate}</TableCell>
                <TableCell>
                  <div className="flex flex-wrap items-center gap-2">
                    <Button variant="secondary" size="sm" onClick={() => handleDownload(doc)}>
                      <Download className="h-3.5 w-3.5" aria-hidden />
                      Download
                    </Button>
                    <Button variant="ghost" size="sm" onClick={() => handleDelete(doc)}>
                      <Trash2 className="h-3.5 w-3.5" aria-hidden />
                      Delete
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}
    </div>
  );
}
