-- Single-use password-reset grants.
--
-- Purely additive: one new table, no foreign keys, nothing existing touched. Safe on a populated
-- database. DDL generated by `prisma migrate diff --from-url <deployed db>` and kept verbatim.
--
-- token_hash holds a SHA-256 of the token, never the token — a leak of this table must not hand
-- anyone working reset links. It is UNIQUE because lookup is by hash equality.

-- CreateTable
CREATE TABLE "password_reset_tokens" (
    "id" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "used_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "password_reset_tokens_token_hash_key" ON "password_reset_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "password_reset_tokens_email_idx" ON "password_reset_tokens"("email");
